#include "Abilities/OCRBMissile.h"

#include "AbilitySystemBlueprintLibrary.h"
#include "AbilitySystemComponent.h"
#include "Components/SphereComponent.h"
#include "GameEffects/GE_MarkEffect.h"
#include "GameFramework/ProjectileMovementComponent.h"
#include "Kismet/GameplayStatics.h"
#include "Particles/ParticleSystemComponent.h"

#include "GameplayEffect.h"
#include "GameplayEffectTypes.h"

AOCRBMissile::AOCRBMissile()
{
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.bStartWithTickEnabled = true;

	// ë„¤íŠ¸ì›Œí¬ ë¦¬í”Œë¦¬ì¼€ì´ì…˜ ì„¤ì •
	bReplicates = true;
	SetReplicateMovement(true);

    // ë©”ì‹œ ì»´í¬ë„ŒíŠ¸
    MeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ProjectileMesh"));
    MeshComponent->SetupAttachment(RootComponent);
    MeshComponent->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	MeshComponent->SetVisibility(true);
	MeshComponent->SetHiddenInGame(false);
    RootComponent = MeshComponent;

    // ì¶©ëŒ ì»´í¬ë„ŒíŠ¸ ìƒì„±
    CollisionComponent = CreateDefaultSubobject<USphereComponent>(TEXT("SphereCollision"));
    CollisionComponent->SetSphereRadius(5.0f);
    CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
    CollisionComponent->SetCollisionObjectType(ECC_WorldDynamic);
    CollisionComponent->SetCollisionResponseToAllChannels(ECR_Block);
    CollisionComponent->SetCollisionResponseToChannel(ECC_Pawn, ECR_Block);
	CollisionComponent->SetVisibility(true);
	CollisionComponent->SetupAttachment(MeshComponent);

    // ë°œì‚¬ì²´ ì´ë™ ì»´í¬ë„ŒíŠ¸
    ProjectileMovement = CreateDefaultSubobject<UProjectileMovementComponent>(TEXT("ProjectileMovement"));
    ProjectileMovement->InitialSpeed = InitialSpeed;
    ProjectileMovement->MaxSpeed = MaxSpeed;
    ProjectileMovement->bRotationFollowsVelocity = true;
    ProjectileMovement->bShouldBounce = false;
	ProjectileMovement->ProjectileGravityScale = 0.0f;
	ProjectileMovement->SetIsReplicated(true);
	    
    // ìœ ë„ ì„¤ì •
    ProjectileMovement->bIsHomingProjectile = true;
    ProjectileMovement->HomingAccelerationMagnitude = HomingAcceleration;

    // íŠ¸ë ˆì¼ ì´í™íŠ¸ 
    TrailEffect = CreateDefaultSubobject<UParticleSystemComponent>(TEXT("TrailEffect"));
    TrailEffect->SetupAttachment(RootComponent);
    TrailEffect->bAutoActivate = true;

    // ìˆ˜ëª… ì„¤ì •
    InitialLifeSpan = LifeSpan;

    // ì¶©ëŒ ì´ë²¤íŠ¸ ë°”ì¸ë”©
    CollisionComponent->OnComponentHit.AddDynamic(this, &AOCRBMissile::OnHit);
}

void AOCRBMissile::BeginPlay()
{
	Super::BeginPlay();
	
	DrawDebugSphere(GetWorld(), GetActorLocation(), 50.0f, 12, FColor::Red, false, 10.0f, 0, 5.0f);
	// ë°œì‚¬ ì‚¬ìš´ë“œ ì¬ìƒ
	if (LaunchSound)
	{
		UGameplayStatics::PlaySoundAtLocation(this, LaunchSound, GetActorLocation());
	}
}

void AOCRBMissile::SetTarget(AActor* NewTarget)
{
	if (IsValid(NewTarget))
	{
		HomingTarget = NewTarget;
		NewTargetInTick=HomingTarget;
		ProjectileMovement->HomingTargetComponent = NewTarget->GetRootComponent();
		ProjectileMovement->bIsHomingProjectile = true;
        
		UE_LOG(LogTemp, Log, TEXT("Homing target set to: %s"), *NewTarget->GetName());
	}
	else
	{
		HomingTarget = nullptr;
		ProjectileMovement->HomingTargetComponent = nullptr;
		ProjectileMovement->bIsHomingProjectile = false;
        
		UE_LOG(LogTemp, Warning, TEXT("Invalid homing target provided"));
	}
}

void AOCRBMissile::OnHit(UPrimitiveComponent* HitComp, AActor* OtherActor, UPrimitiveComponent* OtherComp,
	FVector NormalImpulse, const FHitResult& Hit)
{
	// ìê¸° ìì‹ ì´ë‚˜ ë°œì‚¬ìëŠ” ì œì™¸
	if (OtherActor && OtherActor->IsA(APawn::StaticClass()) && OtherActor != GetOwner())
	{
		UE_LOG(LogTemp, Warning, TEXT("Projectile hit: %s"), *OtherActor->GetName());
		DrawDebugSphere(GetWorld(), GetActorLocation(), 50.0f, 12, FColor::Red, false, 10.0f, 0, 5.0f);
        
		// ì´ë²¤íŠ¸ ë¸Œë¡œë“œìºìŠ¤íŠ¸
		FOnProHit.Broadcast(OtherActor, Hit);
        
		// íˆíŠ¸ ì´í™íŠ¸ ì¬ìƒ
		if (HitEffect)
		{
			UGameplayStatics::SpawnEmitterAtLocation(GetWorld(), HitEffect, Hit.Location, Hit.Normal.Rotation());
		}
        
		// íˆíŠ¸ ì‚¬ìš´ë“œ ì¬ìƒ
		if (HitSound)
		{
			UGameplayStatics::PlaySoundAtLocation(this, HitSound, Hit.Location);
		}

		// ë°œì‚¬ì²´ì—ì„œ ì§ì ‘ í‘œì‹ ì ìš©
		ApplyMarkToTarget(OtherActor);
        
		// ë°œì‚¬ì²´ ì œê±°
		Destroy();
	}
}

void AOCRBMissile::ApplyMarkToTarget(AActor* Target)
{
	if (!HasAuthority() || !MarkEffectClass || !Target) return;
    
	UAbilitySystemComponent* TargetASC = UAbilitySystemBlueprintLibrary::GetAbilitySystemComponent(Target);
	if (!TargetASC) return;
    
	// ë°œì‚¬ì(Owner)ì˜ ASC ì‚¬ìš©
	UAbilitySystemComponent* SourceASC = UAbilitySystemBlueprintLibrary::GetAbilitySystemComponent(GetOwner());
	if (!SourceASC) return;

	UE_LOG(LogTemp, Error, TEXT("ğŸ” BEFORE GE - All target tags: %s"), *TargetASC->GetOwnedGameplayTags().ToStringSimple())
	
	FGameplayEffectContextHandle EffectContext = SourceASC->MakeEffectContext();
	EffectContext.AddSourceObject(this);

	FGameplayEffectSpecHandle SpecHandle = SourceASC->MakeOutgoingSpec(	MarkEffectClass, 1, EffectContext);
	
	//------ì´í™íŠ¸ ì¶”ê°€ ì ìš©
	//FGameplayEffectSpecHandle SpeedSpecHandle = MakeOutgoingGameplayEffectSpec(MarkEffectClass);
	// if (SpeedSpecHandle.IsValid() && SpeedSpecHandle.Data.IsValid())
	// {
	// 	FGameplayEffectSpec* Spec = SpeedSpecHandle.Data.Get();
	//
	// 	Spec->DynamicGrantedTags.AddTag(TAG_Item_SpeedBoost_Active);
	//
	// 	ASC->ApplyGameplayEffectSpecToSelf(*Spec);
	//
	// 	bool bIsServer = (ASC->GetOwnerRole() == ROLE_Authority);
	//
	// 	FGameplayTagContainer OwnedTags;
	// 	ASC->GetOwnedGameplayTags(OwnedTags);
	// }



	if (SpecHandle.IsValid())
	{
		FGameplayEffectSpec* Spec = SpecHandle.Data.Get();
		Spec->DynamicGrantedTags.AddTag(FGameplayTag::RequestGameplayTag(TEXT("State.Marked")));
		//Target->ActorInfo()->ApplyGameplayEffectSpecToSelf(*SpecHandle.Data.Get());
		//FGameplayTagContainer OwnedTags;
		//SourceASC->GetOwnedGameplayTags(OwnedTags);
		SourceASC->ApplyGameplayEffectSpecToTarget(*SpecHandle.Data.Get(), TargetASC);
		

		FActiveGameplayEffectHandle EffectHandle = SourceASC->ApplyGameplayEffectSpecToTarget(*SpecHandle.Data.Get(), TargetASC);
		
		
		// ğŸ” GE ìŠ¤í™ ì •ë³´ ì¶œë ¥
		if (SpecHandle.Data.IsValid())
		{
			const UGameplayEffect* GE = SpecHandle.Data->Def;
			UE_LOG(LogTemp, Error, TEXT("ğŸ” GE Duration Policy: %d"), (int32)GE->DurationPolicy);
			UE_LOG(LogTemp, Error, TEXT("ğŸ” GE Granted Tags Count: %d"), GE->InheritableOwnedTagsContainer.CombinedTags.Num());
            
			for (const FGameplayTag& Tag : GE->InheritableOwnedTagsContainer.CombinedTags)
			{
				UE_LOG(LogTemp, Error, TEXT("ğŸ·ï¸ GE Granted Tag: %s"), *Tag.ToString());
			}
		}
		if (EffectHandle.IsValid())
		{
			UE_LOG(LogTemp, Warning, TEXT("Mark applied to target: %s"), *Target->GetName());
			
			// 0.1ì´ˆ í›„ì— íƒœê·¸ í™•ì¸ (íƒ€ì´ë° ë¬¸ì œ í•´ê²°)
			FTimerHandle TimerHandle;
			GetWorld()->GetTimerManager().SetTimer(TimerHandle, [=]()
			{
				if (IsValid(Target) && IsValid(TargetASC))
				{
					bool bHasMarkTag = TargetASC->HasMatchingGameplayTag(FGameplayTag::RequestGameplayTag(TEXT("State.Marked")));
					UE_LOG(LogTemp, Warning, TEXT("Delayed tag check: %s"), bHasMarkTag ? TEXT("YES! ğŸ‰") : TEXT("Still NO... ğŸ˜¢"));
				}
			}, 0.1f, false);
			
			//SourceASC->ApplyGameplayEffectSpecToTarget(*SpecHandle.Data.Get(), TargetASC);
			// íš¨ê³¼ ì ìš© ì§í›„ íƒœê·¸ í™•ì¸
			//bool bHasMarkTag = TargetASC->HasMatchingGameplayTag(FGameplayTag::RequestGameplayTag(TEXT("State.Marked")));
		}
	}
}

void AOCRBMissile::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
	
	// UE_LOG(LogTemp, Warning, TEXT("AOCRBMissile::Velocity: %s, Location: %s"), *ProjectileMovement->Velocity.ToString(),*GetActorLocation().ToString());
	// if (NewTargetInTick.IsValid())
	// {
	// 	UE_LOG(LogTemp, Warning, TEXT("AOCRBMissile::NewTargetInTick: %s"), *NewTargetInTick->GetActorLocation().ToString());
	// }
}
